package id.my.sendiko.sembako.core.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLightHighContrast = Color(0xFF213100)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF3C4F13)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF282F19)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF444C34)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF00332E)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF22514B)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFAFAEE)
val onBackgroundLightHighContrast = Color(0xFF1A1C15)
val surfaceLightHighContrast = Color(0xFFFAFAEE)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE2E4D4)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2A2D23)
val outlineVariantLightHighContrast = Color(0xFF474A3F)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2F3129)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFB7D085)
val surfaceDimLightHighContrast = Color(0xFFB9BAAF)
val surfaceBrightLightHighContrast = Color(0xFFFAFAEE)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF1F1E6)
val surfaceContainerLightHighContrast = Color(0xFFE3E3D8)
val surfaceContainerHighLightHighContrast = Color(0xFFD5D5CA)
val surfaceContainerHighestLightHighContrast = Color(0xFFC7C7BC)

val primaryDarkHighContrast = Color(0xFFE0FAAB)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFB3CC81)
val onPrimaryContainerDarkHighContrast = Color(0xFF070D00)
val secondaryDarkHighContrast = Color(0xFFEBF4D2)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFBEC6A7)
val onSecondaryContainerDarkHighContrast = Color(0xFF070D01)
val tertiaryDarkHighContrast = Color(0xFFC9FAF2)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF9DCCC4)
val onTertiaryContainerDarkHighContrast = Color(0xFF000E0C)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF12140D)
val onBackgroundDarkHighContrast = Color(0xFFE3E3D8)
val surfaceDarkHighContrast = Color(0xFF12140D)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF45483C)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF0F1E1)
val outlineVariantDarkHighContrast = Color(0xFFC2C4B5)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE3E3D8)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF3B4E12)
val surfaceDimDarkHighContrast = Color(0xFF12140D)
val surfaceBrightDarkHighContrast = Color(0xFF4F5148)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1E2019)
val surfaceContainerDarkHighContrast = Color(0xFF2F3129)
val surfaceContainerHighDarkHighContrast = Color(0xFF3A3C34)
val surfaceContainerHighestDarkHighContrast = Color(0xFF46483F)







